//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGroup
    {
        public Nullable<long> CustomerID { get; set; }
        public string Name { get; set; }
        public long GroupID { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> CsrID { get; set; }
        public string RegNo { get; set; }
        public string GroupPrevNo { get; set; }
        public string VillageWardNo { get; set; }
        public string LandMark { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public string MeetingPlace { get; set; }
        public string UnitNo { get; set; }
        public Nullable<int> ActiveStatus { get; set; }
        public Nullable<int> DeleteStatus { get; set; }
    }
}
